docs_dir: docs/book
site_dir: docs/html
pages:
    - Home: index.md
    - Introduction: intro.md
    - Reference:
      - Specifications: specs.md
      - "File Upload Input": file-input.md
      - "Optional Input Filters": optional-input-filters.md
      - "Unfiltered Data": unfiltered-data.md
site_name: zend-inputfilter
site_description: 'Normalize and validate input sets from the web, APIs, the CLI, and more, including files.'
repo_url: 'https://github.com/zendframework/zend-inputfilter'
