docs_dir: docs/book
site_dir: docs/html
nav:
    - index.md
    - Intro: intro.md
    - Specifications: specs.md
    - Files: file-input.md
site_name: laminas-inputfilter
site_description: laminas-inputfilter
repo_url: 'https://github.com/laminas/laminas-inputfilter'
