docs_dir: docs/book
site_dir: docs/html
nav:
    - Home: index.md
    - Introduction: intro.md
    - Reference:
      - Specifications: specs.md
      - Files: file-input.md
      - "Optional Input Filters": optional-input-filters.md
      - "Unfiltered Data": unfiltered-data.md
site_name: laminas-inputfilter
site_description: laminas-inputfilter
repo_url: 'https://github.com/laminas/laminas-inputfilter'
