docs_dir: docs/book
site_dir: docs/html
pages:
    - Home: index.md
    - Introduction: intro.md
    - Reference:
      - Specifications: specs.md
      - "File Upload Input": file-input.md
      - "Optional Input Filters": optional-input-filters.md
      - "Unfiltered Data": unfiltered-data.md
    - "Application Integration":
        - "Usage in a zend-mvc application": application-integration/usage-in-a-zend-mvc-application.md
        - "Usage in a zend-expressive application": application-integration/usage-in-a-zend-expressive-application.md
site_name: zend-inputfilter
site_description: 'Normalize and validate input sets from the web, APIs, the CLI, and more, including files.'
repo_url: 'https://github.com/zendframework/zend-inputfilter'
